name: Html Website Check
on:
    push:
        pull_request:
          jobs:
            check-html:
              runs on: ubuntu-latest:
                steps:
                - name: checkout repository
                uses: actions/checkout@v4

              - name: check index.html
              run:
                test -f index.html
                echo "index.html exists"

              - name: check dummy2.html
              run:
                test -f dummy2.html
                echo "dummy2.html"

              - name: Test completed
              run: echo "HTML files checked successfully!"


